default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: ivik

development:
  <<: *default
  database: jetthoughts_development
  password: ENV[LOCAL_POSTGESQL_PASSWD]

test:
  <<: *default
  database: jetthoughts_test
  password: ENV[LOCAL_POSTGESQL_PASSWD]

production:
  <<: *default
  database: jetthoughts_production
  username: jetthoughts
  password: <%= ENV['JETTHOUGHTS_DATABASE_PASSWORD'] %>
