# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d2c45aad17d9d848e843fed4fcc5d4237b3cd4383615fb14b6b22cab29f89f6bac66fc4a3095d2229f60bdb1b749e3ee3eafd1b19c20705032cfb9d1863ecb81

test:
  secret_key_base: 7c1d766bf984cb3b4ccf1f0061e22ad0d890ab1ed1d4681192527364c9291a51f6bb3db75b16c9aec94e7ba6c51edbd38792a559b2b260afe5c05a2fa3e8d551

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
